services:
  yarn:
    depends_on: 
      - db
    restart: always
    volumes:
      - .:/app

  db:
    image: postgres
    restart: always
    env_file: 
      - .env
    volumes:
      - ./data/pg:/var/lib/postgresql/data