services:
  bot:
    depends_on: 
      - db
      - oauth
    # restart: always
    env_file:
    - .env
    networks:
    - yarn

  oauth:
    build:
      context: packages/yarn-oauth
      dockerfile: Dockerfile
    env_file:
    - .env
    networks:
    - yarn


  db:
    image: postgres
    restart: always
    env_file: 
      - .env
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - yarn

networks:
  yarn: